version: '3.8'
services:
    app:
      container_name: application
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        - SPRING_DATABASE_URL=jdbc:postgresql://db:5432/postgres
        - SPRING_DATABASE_USERNAME=postgres
        - SPRING_DATABASE_PASSWORD=12345678

    db:
      container_name: database
      image: postgres:13.1
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345678
      ports:
        - "5432:5432"
      volumes:
        # - ./init:/docker-entrypoint-initdb.d
        - ./pgdata:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      depends_on:
        - db
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=12345678
      ports:
        - "5050:80"